# Generated by Django 5.0.3 on 2024-03-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade_rel', models.IntegerField(default=0)),
                ('lampada', models.BooleanField(default=False)),
                ('tempo_ciclo', models.DurationField()),
                ('tempo_total', models.DurationField()),
            ],
        ),
    ]
