# Generated by Django 5.0.3 on 2024-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade', models.IntegerField()),
                ('lampada', models.BooleanField(default=False)),
                ('tempo_ciclo', models.TimeField()),
                ('tempo_total', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DadosSensor',
        ),
    ]
